name: 'Automatischer PR-Kommentar'

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: FÃ¼ge automatischen Kommentar hinzu
        uses: mshick/add-pr-comment@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ğŸ‘‹ **Vielen Dank** fÃ¼r das Ã–ffnen dieses Pull Requests, **@${{ github.event.pull_request.user.login }}**!

            Wir haben Ihren Beitrag erhalten und werden ihn in KÃ¼rze Ã¼berprÃ¼fen.

            Bitte stellen Sie sicher, dass Sie:
            * [ ] Die **Tests** lokal ausgefÃ¼hrt haben.
            * [ ] Die **Dokumentation** bei Bedarf aktualisiert haben.
            * [ ] Eine aussagekrÃ¤ftige **Beschreibung** hinzugefÃ¼gt haben.

            [Weitere Infos zu unseren Beitrag-Richtlinien](https://example.com/contribution-guidelines)
